<?php
/**
 * db_class.php — the database base class every Model extends.
 *
 * MVC note: this is Model infrastructure. It knows how to connect to MySQL
 * and how to run *prepared* statements safely. It never echoes HTML and
 * never reads $_POST/$_GET/$_SESSION — child model classes (Customer,
 * Product, Cart) inherit fetchAll()/fetchOne()/execute() and add the SQL.
 *
 * Uses PDO (the spec allows "PDO/MySQLi"). PDO gives us one clean prepared
 * statement helper set and exception-based error handling.
 */

require_once __DIR__ . '/db_cred.php';

class Database
{
    /** PDO connection — private so only this class touches it directly. */
    private $conn;

    public function __construct()
    {
        try {
            $this->conn = new PDO(
                'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4',
                DB_USER,
                DB_PASS,
                [
                    // Throw exceptions on error instead of silent failures.
                    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                    // Rows come back as associative arrays by default.
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    // Use real prepared statements, not emulated ones.
                    PDO::ATTR_EMULATE_PREPARES   => false,
                ]
            );
        } catch (PDOException $e) {
            // Log the real reason, show the user something generic.
            if (function_exists('log_error')) {
                log_error('DB connection failed: ' . $e->getMessage());
            } else {
                error_log('DB connection failed: ' . $e->getMessage());
            }
            die('Database connection failed. Please try again later.');
        }
    }

    /**
     * Run a SELECT that may return many rows.
     * @return array list of associative rows (empty array if none)
     */
    public function fetchAll($sql, $params = [])
    {
        $stmt = $this->conn->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

    /**
     * Run a SELECT expected to return a single row.
     * @return array|false the row, or false if nothing matched
     */
    public function fetchOne($sql, $params = [])
    {
        $stmt = $this->conn->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetch();
    }

    /**
     * Run an INSERT / UPDATE / DELETE.
     * @return bool true on success
     */
    public function execute($sql, $params = [])
    {
        $stmt = $this->conn->prepare($sql);
        return $stmt->execute($params);
    }

    /** ID generated by the most recent INSERT on this connection. */
    public function lastInsertId()
    {
        return $this->conn->lastInsertId();
    }

    /** Raw PDO handle, for the rare case a child needs transactions etc. */
    public function getConnection()
    {
        return $this->conn;
    }
}
